### ISSUE TITLE
questions séries temporelles

### ISSUE THREAD

**Issue by celiamabille** [BioDataScience-Course/sdd3-19m-ts-celiamabille#1]
bonjour @GuyliannEngels @phgrosjean , 

j'ai quelques question concernant les séries temporelles:

- je ne vois pas trop à quoi sert la fonction unclass. Elle est supposée enlever la valeur class mais un vecteur est créé à la suite de l'appel de la fonction.
- lorsque l'on réalise l'acf je ne vois pas pourquoi dans certains cas il n'y a pas de corrélation. A moins que celle-ci a été réalisée sur la série décalée mais dans ce cas comment savoir comment elle a été décalée? Et à quoi correspond l'axe des abscisses lorsque l'acf est représentée? 

d'avance merci

**Comment by phgrosjean** [comment]
- La fonction unclass() enlève simplement la classe de l'objet. Du coup quand on imprime l'objet "déclassé", la méthode de cette objet n'est plus invoquée et le contenu véritable apparait visible. C'est une astuce pour voir comment est construit un objet. Ici, c'est un vecteur (ts) ou une matrice (mts) avec un attribut "tsp" en plus.

- L'axe des abscisses est le décalage. On calcule l'autocorrélation pour un décalage de 0, 1, 2, 3, 4, 5, ... et à chaque fois cela donne une barre verticale sur le graphique. Ce qui te perturbe est sans doute que cet axe X n'est pas libellé en nombre de décalage, mais en décalage exprimé en unité de temps. Donc, 0/12 d'année, 1/12 d'année, 2/12 d'année, etc. pour nottem part exemple.
